//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaStoreUI.MVC.PizzaStoreDataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStoreData.DataService")]
    [System.SerializableAttribute()]
    public partial class OrderDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaymentMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SubtotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TaxesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((this.CustomerField.Equals(value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentMethod {
            get {
                return this.PaymentMethodField;
            }
            set {
                if ((this.PaymentMethodField.Equals(value) != true)) {
                    this.PaymentMethodField = value;
                    this.RaisePropertyChanged("PaymentMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Subtotal {
            get {
                return this.SubtotalField;
            }
            set {
                if ((this.SubtotalField.Equals(value) != true)) {
                    this.SubtotalField = value;
                    this.RaisePropertyChanged("Subtotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Taxes {
            get {
                return this.TaxesField;
            }
            set {
                if ((this.TaxesField.Equals(value) != true)) {
                    this.TaxesField = value;
                    this.RaisePropertyChanged("Taxes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentMethodDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStoreData.DataService.Models")]
    [System.SerializableAttribute()]
    public partial class PaymentMethodDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PizzaDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStoreData.DataService.Models")]
    [System.SerializableAttribute()]
    public partial class PizzaDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CheeseTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrustTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PizzaSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SauceTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CheeseType {
            get {
                return this.CheeseTypeField;
            }
            set {
                if ((this.CheeseTypeField.Equals(value) != true)) {
                    this.CheeseTypeField = value;
                    this.RaisePropertyChanged("CheeseType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrustType {
            get {
                return this.CrustTypeField;
            }
            set {
                if ((this.CrustTypeField.Equals(value) != true)) {
                    this.CrustTypeField = value;
                    this.RaisePropertyChanged("CrustType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order {
            get {
                return this.OrderField;
            }
            set {
                if ((this.OrderField.Equals(value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PizzaSize {
            get {
                return this.PizzaSizeField;
            }
            set {
                if ((this.PizzaSizeField.Equals(value) != true)) {
                    this.PizzaSizeField = value;
                    this.RaisePropertyChanged("PizzaSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SauceType {
            get {
                return this.SauceTypeField;
            }
            set {
                if ((this.SauceTypeField.Equals(value) != true)) {
                    this.SauceTypeField = value;
                    this.RaisePropertyChanged("SauceType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PizzaSizeDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStoreData.DataService.Models")]
    [System.SerializableAttribute()]
    public partial class PizzaSizeDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrustTypeDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStoreData.DataService")]
    [System.SerializableAttribute()]
    public partial class CrustTypeDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SauceTypeDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStoreData.DataService.Models")]
    [System.SerializableAttribute()]
    public partial class SauceTypeDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheeseTypeDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStoreData.DataService")]
    [System.SerializableAttribute()]
    public partial class CheeseTypeDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToppingDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStoreData.DataService")]
    [System.SerializableAttribute()]
    public partial class ToppingDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((this.CategoryField.Equals(value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToppingCategoryDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStoreData.DataService")]
    [System.SerializableAttribute()]
    public partial class ToppingCategoryDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToppingPlacementDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStoreData.DataService")]
    [System.SerializableAttribute()]
    public partial class ToppingPlacementDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToppingListDAO", Namespace="http://schemas.datacontract.org/2004/07/PizzaStoreData.DataService")]
    [System.SerializableAttribute()]
    public partial class ToppingListDAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PizzaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlacementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToppingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pizza {
            get {
                return this.PizzaField;
            }
            set {
                if ((this.PizzaField.Equals(value) != true)) {
                    this.PizzaField = value;
                    this.RaisePropertyChanged("Pizza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Placement {
            get {
                return this.PlacementField;
            }
            set {
                if ((this.PlacementField.Equals(value) != true)) {
                    this.PlacementField = value;
                    this.RaisePropertyChanged("Placement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Topping {
            get {
                return this.ToppingField;
            }
            set {
                if ((this.ToppingField.Equals(value) != true)) {
                    this.ToppingField = value;
                    this.RaisePropertyChanged("Topping");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PizzaStoreDataService.IPizzaStoreDataService")]
    public interface IPizzaStoreDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetOrders", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetOrdersResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.OrderDAO[] GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetOrders", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetOrdersResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.OrderDAO[]> GetOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetPaymentMethods", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetPaymentMethodsResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.PaymentMethodDAO[] GetPaymentMethods();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetPaymentMethods", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetPaymentMethodsResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.PaymentMethodDAO[]> GetPaymentMethodsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/postOrder", ReplyAction="http://tempuri.org/IPizzaStoreDataService/postOrderResponse")]
        bool postOrder(PizzaStoreUI.MVC.PizzaStoreDataService.OrderDAO newOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/postOrder", ReplyAction="http://tempuri.org/IPizzaStoreDataService/postOrderResponse")]
        System.Threading.Tasks.Task<bool> postOrderAsync(PizzaStoreUI.MVC.PizzaStoreDataService.OrderDAO newOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetPizzas", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetPizzasResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.PizzaDAO[] GetPizzas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetPizzas", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetPizzasResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.PizzaDAO[]> GetPizzasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetPizzaSizes", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetPizzaSizesResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.PizzaSizeDAO[] GetPizzaSizes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetPizzaSizes", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetPizzaSizesResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.PizzaSizeDAO[]> GetPizzaSizesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetCrustTypes", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetCrustTypesResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.CrustTypeDAO[] GetCrustTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetCrustTypes", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetCrustTypesResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.CrustTypeDAO[]> GetCrustTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetSauceTypes", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetSauceTypesResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.SauceTypeDAO[] GetSauceTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetSauceTypes", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetSauceTypesResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.SauceTypeDAO[]> GetSauceTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetCheeseTypes", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetCheeseTypesResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.CheeseTypeDAO[] GetCheeseTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetCheeseTypes", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetCheeseTypesResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.CheeseTypeDAO[]> GetCheeseTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetToppings", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetToppingsResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.ToppingDAO[] GetToppings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetToppings", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetToppingsResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.ToppingDAO[]> GetToppingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetToppingCategories", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetToppingCategoriesResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.ToppingCategoryDAO[] GetToppingCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetToppingCategories", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetToppingCategoriesResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.ToppingCategoryDAO[]> GetToppingCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetToppingPlacements", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetToppingPlacementsResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.ToppingPlacementDAO[] GetToppingPlacements();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetToppingPlacements", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetToppingPlacementsResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.ToppingPlacementDAO[]> GetToppingPlacementsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetToppingLists", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetToppingListsResponse")]
        PizzaStoreUI.MVC.PizzaStoreDataService.ToppingListDAO[] GetToppingLists();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPizzaStoreDataService/GetToppingLists", ReplyAction="http://tempuri.org/IPizzaStoreDataService/GetToppingListsResponse")]
        System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.ToppingListDAO[]> GetToppingListsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPizzaStoreDataServiceChannel : PizzaStoreUI.MVC.PizzaStoreDataService.IPizzaStoreDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PizzaStoreDataServiceClient : System.ServiceModel.ClientBase<PizzaStoreUI.MVC.PizzaStoreDataService.IPizzaStoreDataService>, PizzaStoreUI.MVC.PizzaStoreDataService.IPizzaStoreDataService {
        
        public PizzaStoreDataServiceClient() {
        }
        
        public PizzaStoreDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PizzaStoreDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PizzaStoreDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PizzaStoreDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.OrderDAO[] GetOrders() {
            return base.Channel.GetOrders();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.OrderDAO[]> GetOrdersAsync() {
            return base.Channel.GetOrdersAsync();
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.PaymentMethodDAO[] GetPaymentMethods() {
            return base.Channel.GetPaymentMethods();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.PaymentMethodDAO[]> GetPaymentMethodsAsync() {
            return base.Channel.GetPaymentMethodsAsync();
        }
        
        public bool postOrder(PizzaStoreUI.MVC.PizzaStoreDataService.OrderDAO newOrder) {
            return base.Channel.postOrder(newOrder);
        }
        
        public System.Threading.Tasks.Task<bool> postOrderAsync(PizzaStoreUI.MVC.PizzaStoreDataService.OrderDAO newOrder) {
            return base.Channel.postOrderAsync(newOrder);
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.PizzaDAO[] GetPizzas() {
            return base.Channel.GetPizzas();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.PizzaDAO[]> GetPizzasAsync() {
            return base.Channel.GetPizzasAsync();
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.PizzaSizeDAO[] GetPizzaSizes() {
            return base.Channel.GetPizzaSizes();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.PizzaSizeDAO[]> GetPizzaSizesAsync() {
            return base.Channel.GetPizzaSizesAsync();
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.CrustTypeDAO[] GetCrustTypes() {
            return base.Channel.GetCrustTypes();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.CrustTypeDAO[]> GetCrustTypesAsync() {
            return base.Channel.GetCrustTypesAsync();
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.SauceTypeDAO[] GetSauceTypes() {
            return base.Channel.GetSauceTypes();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.SauceTypeDAO[]> GetSauceTypesAsync() {
            return base.Channel.GetSauceTypesAsync();
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.CheeseTypeDAO[] GetCheeseTypes() {
            return base.Channel.GetCheeseTypes();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.CheeseTypeDAO[]> GetCheeseTypesAsync() {
            return base.Channel.GetCheeseTypesAsync();
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.ToppingDAO[] GetToppings() {
            return base.Channel.GetToppings();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.ToppingDAO[]> GetToppingsAsync() {
            return base.Channel.GetToppingsAsync();
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.ToppingCategoryDAO[] GetToppingCategories() {
            return base.Channel.GetToppingCategories();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.ToppingCategoryDAO[]> GetToppingCategoriesAsync() {
            return base.Channel.GetToppingCategoriesAsync();
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.ToppingPlacementDAO[] GetToppingPlacements() {
            return base.Channel.GetToppingPlacements();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.ToppingPlacementDAO[]> GetToppingPlacementsAsync() {
            return base.Channel.GetToppingPlacementsAsync();
        }
        
        public PizzaStoreUI.MVC.PizzaStoreDataService.ToppingListDAO[] GetToppingLists() {
            return base.Channel.GetToppingLists();
        }
        
        public System.Threading.Tasks.Task<PizzaStoreUI.MVC.PizzaStoreDataService.ToppingListDAO[]> GetToppingListsAsync() {
            return base.Channel.GetToppingListsAsync();
        }
    }
}
