//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaStoreData.DataService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PizzaStoreDBEntities : DbContext
    {
        public PizzaStoreDBEntities()
            : base("name=PizzaStoreDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<CheeseType> CheeseTypes { get; set; }
        public virtual DbSet<CrustType> CrustTypes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DaysOpen> DaysOpens { get; set; }
        public virtual DbSet<DaysOpenEntry> DaysOpenEntries { get; set; }
        public virtual DbSet<DayTitle> DayTitles { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<Pizza> Pizzas { get; set; }
        public virtual DbSet<PizzaSize> PizzaSizes { get; set; }
        public virtual DbSet<SauceType> SauceTypes { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<ToppingCategory> ToppingCategories { get; set; }
        public virtual DbSet<ToppingList> ToppingLists { get; set; }
        public virtual DbSet<ToppingPlacement> ToppingPlacements { get; set; }
        public virtual DbSet<Topping> Toppings { get; set; }
    }
}
