//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaStoreData.DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Pizza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pizza()
        {
            this.ToppingLists = new HashSet<ToppingList>();
        }

        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public int PizzaSizeId { get; set; }
        [DataMember]
        public int CrustTypeId { get; set; }
        [DataMember]
        public int SauceTypeId { get; set; }
        [DataMember]
        public int CheeseTypeId { get; set; }
        [DataMember]
        public int OrderId { get; set; }
    
        public virtual CheeseType CheeseType { get; set; }
        public virtual CrustType CrustType { get; set; }
        public virtual Order Order { get; set; }
        public virtual PizzaSize PizzaSize { get; set; }
        public virtual SauceType SauceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToppingList> ToppingLists { get; set; }
    }
}
